### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tr90814** [tr90814/farewill#65]
- [ ] spacing of add asset text different in categories

- [ ] pets text colour wrong

- [ ] you can still click on locked categories

- [ ] need to clear out notifications

- [ ] make buttons larger for things and decisions

- [ ] things and decisions position moves around

- [ ] group description on splash page isn’t aligned

- [ ] Make add person image thing really big

- [ ] initialisation of draggles

- [ ] Fix upload area CSS

- [ ] Draggable is not draggable when added a name

- [ ] residual stuff icon

- [ ] Add person, first time drop doesnt work

- [ ] when you add a message and submit it, the css fucks up on the person icon

- [ ] css of blue bit is a bit fucked when a message is added

- [ ] asset default image.jpg (make default everythign else icon)

- [ ] CHILD'S DATE OF BIRTH

- [ ] CHILDS NAME

- [ ] NUMBER OF CHILDREN

**Comment by anttonp** [comment]
Change "residual" to "everything else"

Show names under the blocks in scroll

Change "first interaction text" = Who would you like to leave everything to?

Add #tip6 (display:hidden right now).

Reduce the text of the tips.

Default picture changes colour. 

Video on splash page

**Comment by tr90814** [comment]
I need to sort some stuff for going away this eve, if I have time i'll tackle some of the important harder todos.

**Comment by anttonp** [comment]
I was planning on making the most of them myself. Ill just need some help with a couple of the points. I'll let u know!

**Comment by tr90814** [comment]
perfect

**Comment by anttonp** [comment]
In safari, you cannot clink in "upload" or "Click" 
![screen shot 2015-06-25 at 17 46 06](https://cloud.githubusercontent.com/assets/11814997/8360081/519c5e2c-1b62-11e5-8daf-03e47b6f9215.png)
